trigger:
- main

pool:
  name: nopCommerce_pool

steps:
- task: UseDotNet@2
  displayName: "Instalar .NET SDK 9"
  inputs:
    packageType: 'sdk'
    version: '9.0.x'
    includePreviewVersions: true

- script: dotnet restore src/Presentation/Nop.Web/Nop.Web.csproj
  displayName: "Restore"

- script: dotnet build src/Presentation/Nop.Web/Nop.Web.csproj -c Release
  displayName: "Build"

- script: dotnet publish src/Presentation/Nop.Web/Nop.Web.csproj -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: "Publish"

- task: ArchiveFiles@2
  displayName: "Generar ZIP de publicaci√≥n"
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/nop.zip'
    replaceExistingArchive: true

- task: AzureRmWebAppDeployment@5
  displayName: "Despliegue a Azure App Service Linux"
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(d661f6b6-51be-46ec-a355-52db3499fb73)'
    appType: 'webAppLinux'
    WebAppName: 'nopCommerceLinux'
    package: '$(Build.ArtifactStagingDirectory)/nop.zip'
