trigger:
- main

pool:
  name: nopCommerce_pool

steps:

# --- Instalar .NET 9 (coincide con global.json) ---
- task: UseDotNet@2
  displayName: "Instalar .NET SDK 9"
  inputs:
    packageType: 'sdk'
    version: '9.0.x'
    includePreviewVersions: true

# --- (Opcional) verificar instalación ---
- script: |
    dotnet --version
    dotnet --list-sdks
  displayName: "Verificar SDK instalado"

# --- Compilación ---
- task: DotNetCoreCLI@2
  displayName: "Compilación"
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    workingDirectory: '$(System.DefaultWorkingDirectory)/src'

# --- Publicación ---
- task: DotNetCoreCLI@2
  displayName: "Publicación"
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    workingDirectory: '$(System.DefaultWorkingDirectory)/src'

# --- Pruebas ---
- task: DotNetCoreCLI@2
  displayName: "Pruebas"
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'
    publishTestResults: true

# --- Despliegue a Azure App Service ---
- task: AzureRmWebAppDeployment@5
  displayName: "Despliegue"
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(d661f6b6-51be-46ec-a355-52db3499fb73)'
    appType: 'webApp'
    WebAppName: 'nopCommerce'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
