trigger:
- main

pool:
  name: nopCommerce_pool

steps:
- task: UseDotNet@2
  displayName: "Instalar .NET SDK 9"
  inputs:
    packageType: 'sdk'
    version: '9.0.x'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: "Compilación"
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    workingDirectory: '$(System.DefaultWorkingDirectory)/src'

- task: DotNetCoreCLI@2
  displayName: "Publicación"
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    workingDirectory: '$(System.DefaultWorkingDirectory)/src'

- task: DotNetCoreCLI@2
  displayName: "Pruebas"
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'
    publishTestResults: true

- task: AzureRmWebAppDeployment@5
  displayName: "Despliegue"
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(d661f6b6-51be-46ec-a355-52db3499fb73)'
    appType: 'webApp'
    WebAppName: 'nopCommerce'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
